[project]
name = "risk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter==1.1.1",
    "matplotlib==3.10.8",
    "pandas==3.0.1",
    "scipy==1.17.1",
    "seaborn==0.13.2",
]
